[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ibc-api"
version = "0.1"
requires-python = ">=3.7"
dependencies = [
    "siibra",
    "nibabel",
    "pandas",
    "tqdm"
]